routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });


 Route::get('/', 'Front\HomeController@maintence');
 Route::get('/manutencao', 'Front\HomeController@index');
 Route::get('escritorio', 'Front\OfficeController@index');
 Route::get('atuacao', 'Front\ActuationsController@index');
 Route::get('atuacao/{slugAtuacao}', 'Front\ActuationsController@show');
 Route::get('/profissionais', 'Front\ProfessionalsController@index');

 Route::get('noticias', 'Front\BlogsController@index');
 Route::get('noticias/{slugBlog}', 'Front\BlogsController@show');
 Route::get('/depoimentos', 'Front\ReviewController@index');
 Route::post('/depoimentos-create', 'Front\ReviewController@store');
 Route::get('/contato', 'Front\ContactController@index');


// Route::get('/reservas', 'Front\ReservationController@index');
// Route::get('/banco-reservas', 'Front\ReservationController@view')->name('bank.index');
// Route::get('/banco-reservas/{name}', 'Front\ReservationController@show')->name('bank.show');
// Route::get('/banco-reservas/{name}/info/{reservation}', 'Front\ReservationController@info')->name('bank.info');

 Route::prefix('services')->namespace('Services')->group(function() {
     Route::post('send-mail', 'MailController@sendContact');
//     Route::prefix('newsletter')->group(function() {
//         Route::post('/', 'MailController@subscribe');
//         Route::get('confirm/{code}', 'MailController@confirmSubscribe');
//     });
//     Route::apiResource('pre-registration', 'PreRegistrationController');
//     Route::get('reservations', 'ReservationsController@index');
//     Route::delete('reservations/{reservation}', 'ReservationsController@destroy');
//     Route::match(['patch','put'], 'reservations', 'ReservationsController@update');

//     Route::post('bank-reservations/{reservation}/interest', 'BankReservationController@interest');
//     Route::delete('bank-reservations/interest/{reservation_interest}', 'BankReservationController@destroy');
//     Route::match(['patch','put'],'bank-reservations/interest/{reservation_interest}', 'BankReservationController@update');
 });


Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');
    Route::resource('office', 'Admin\OfficeController');
    Route::get('office-photos', ['as' => 'office-photos', 'uses' => 'Admin\OfficeController@photos']);
    Route::post('office-upload', ['as' => 'office-upload', 'uses' => 'Admin\OfficeController@upload']);
    Route::get('office-download/{officeId}/{photoId}', ['as' => 'office-download', 'uses' => 'Admin\OfficeController@download']);
	Route::get('office-destroy/{officeId}/{photoId}', ['as' => 'office-destroy', 'uses' => 'Admin\OfficeController@destroy']);


	Route::resource('actuations', 'Admin\ActuationsController');
	Route::resource('professionals', 'Admin\ProfessionalsController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::resource('reviews', 'Admin\ReviewsController');


    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('clients', 'Admin\ClientsController');
	Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    Route::view('pre-registrations', 'admin.pre-registrations.index')->name('pre-registrations.index');
    Route::get('reservations', 'Admin\ReservationsController@index')->name('reservations.index');
    Route::match(['GET', 'POST'], 'reservations/new', 'Admin\ReservationsController@insert')->name('reservations.insert');
    Route::match(['GET', 'PUT'],'reservations/{reservation}', 'Admin\ReservationsController@viewOrUpdate')->name('reservations.viewOrUpdate');
    Route::get('reservations/{id}/ficha', 'Admin\ReservationsController@create')->name('reservations.create');
    Route::post('reservations/{id}/ficha', 'Admin\ReservationsController@store')->name('reservations.store');
});

Auth::routes();

app/Models/Office.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Office extends Model
{
    protected $fillable = [
    	'page_description'
    ];

    public function photos(){
    	return $this->hasMany('App\Models\OfficePhotos');
    }
}

app/Http/Controllers/Admin/OfficeController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\Office\StoreRequest;
//use App\Http\Requests\Admin\Office\UpdateRequest;

use App\Models\Office;

class OfficeController extends Controller
{
    /**
     * Armazena uma nova instancia do model Office
     *
     * @var \App\Office
     */
    private $offices;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
      $this->offices = app(Office::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $office = Office::firstOrFail();
      return view('admin.offices.index', compact('office'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {

      $office = $this->offices->firstOrFail();

      if(!$office) {
        session()->flash('messages.error', ['Quem Somos não existe!']);
        return redirect()->route('office.index');
      }

      $office->page_description = $request->page_description;
      $office->save();

      session()->flash('messages.success', ['Quem Somos alterado com sucesso!']);
      return redirect()->route('office.index');

    }


    public function photos()
    {
      $office = \App\Models\Office::with('photos')->find(1);
      return view('admin.offices.photos', compact('office'));
    }

    public function upload()
    {
      $file = \Request::file('documento');
      $officeid = \Request::get('officeid');
      $storagePath = $file->store('office');
      $fileName = $storagePath;

      $fileModel = new \App\Models\OfficePhotos();
      $fileModel->name = $fileName;

      $office = \App\Models\Office::find($officeid);
      $office->photos()->save($fileModel);
    }

    public function download($officeId, $photoId)
    {
      $file = \App\Models\OfficePhotos::find($photoId);
      $storagePath = $file->store('office');
      return \Response::download($storagePath.'/'.$file->name);
      
    }
    public function destroy($officeId, $photoId)
    {
      $file = \App\Models\OfficePhotos::find($photoId);
      $storagePath = 'storage';
      $file->delete();
      unlink($storagePath.'/'.$file->name);

      session()->flash('messages.success', ['Foto deletada com sucesso!']);
      return redirect()->route('office-photos');
    }


  }

app/Http/Controllers/Front/OfficeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OfficeController extends Controller
{
    public function index()
    {
    	return view('front.office');
    }
}

resources/views/admin/offices/index.blade.php
@extends('admin.base')
@section('title', 'Editar O Escritório')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  @include('elements.messages')

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title')
         </div>

         <div class="panel-body">

          <form action="{{ route('office.store')}}" enctype="multipart/form-data" method="POST">
            {!! csrf_field() !!}

            <div class="row">
              <div class="col-xs-12 col-md-12">

                <div class="form-group @if ($errors->has('page_description')) has-error @endif">
                  <label for="page_description" class="form-label">Descrição da Página</label>
                  <textarea rows="18" class="form-control textarea" id="page_description" name="page_description" value="{{ $offices->page_description ?? old('page_description') }}" placeholder="Descrição da Página" autofocus>{{ $offices->page_description ?? old('page_description') }}</textarea>
                  @if ($errors->has('page_description'))
                  <span class="help-block">
                    <strong>{{ $errors->first('page_description') }}</strong>
                  </span>
                  @endif
                </div><!-- form-group -->
                
                <div class="form-group">
                  <a href="{{ url('/dashboard/office-photos') }}" class="btn btn-success"><i class="fa fa-image"></i> Galeria de Fotos</a>
                </div>


              </div>
            </div>
            

          </div><!-- col-md-11 -->

          <div class="row">
            <div class="col-md-6">
              <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
              <a href="{{ url('/dashboard') }}" class="btn btn-sm btn-warning"><i class="fa fa-reply"></i> Cancelar</a>
            </div><!-- col-md-6 -->
          </div>

        </form>

      </div><!-- panel-body -->


    </div><!-- panel-default -->
  </div><!-- col-md-12 -->


</div><!-- row -->
</div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection


@section('cssPage')
<link rel="stylesheet" href="/bower_components/blueimp-file-upload/css/jquery.fileupload.css">
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();

  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="title"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="url"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>
@endsection

resources/views/admin/offices/photos.blade.php
@extends('admin.base')
@section('title', 'Galeria do Escritório')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  @include('elements.messages')

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title')
         </div>

         <div class="panel-body">




          <div class="row">
            <div class="col-xs-12 col-md-12">

              <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>Selecionar Fotos</span>
                <!-- The file input field used as target for the file upload widget -->
                <input id="fileupload" type="file" name="documento" data-token="{!! csrf_token() !!}" data-officeid="{{ $offices->id }}">
              </span>
              <br>
              <br>
              <!-- The global progress bar -->
              <div id="progress" class="progress">
                <div class="progress-bar progress-bar-success"></div>
              </div>
              <!-- The container for the uploaded files -->
              <div id="files" class="files"></div>

            </div>
            <hr class="invisible clearfix">
            <div class="col-xs-12 col-md-12">
              <table class="table table-bordered table-striped table-hover">
                <thead>
                  <th>Imagem</th>
                  <th>Enviado em</th>
                  <th>Ações</th>
                </thead>
                <tbody>
                  @foreach($office->photos as $photo)
                  <tr>
                    <td><img src="/storage/{!! $photo->name !!}" alt="{!! $photo->name !!}" class="img-rounded" style="width:90px;"></td>
                    <td>{!! $photo->created_at !!}</td>
                    <td>
                      <a href="{!! route('office-download', [$office->id, $photo->id]) !!}" class="btn btn-xs btn-success"><i class="fa fa-download"></i></a>
                      <a href="{!! route('office-destroy', [$office->id, $photo->id]) !!}" class="btn btn-xs btn-danger"><i class="fa fa-remove"></i></a>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>


        </div><!-- col-md-11 -->

        <div class="row">
          <hr class="invisible clearfix">
          <div class="col-md-6">
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
            <a href="{{ url('/dashboard') }}" class="btn btn-sm btn-warning"><i class="fa fa-reply"></i> Cancelar</a>
          </div><!-- col-md-6 -->
        </div>

      </div><!-- panel-body -->


    </div><!-- panel-default -->
  </div><!-- col-md-12 -->


</div><!-- row -->
</div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
<link rel="stylesheet" href="/bower_components/blueimp-file-upload/css/jquery.fileupload.css">
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
  /* BOOTSTRAP WYSIHTML5 */
  $('.textarea').wysihtml5();

  /* SUMMERNOTE*/
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
  $('input[name="title"]').stringToSlug({
    setEvents: 'keyup keydown blur',
    getPut: 'input[name="url"]',
    space: '-',
    replace: '/\s?\([^\)]*\)/gi',
    AND: 'e'
  });
</script>

<script src="/bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget.js"></script>
<script src="/bower_components/blueimp-file-upload/js/jquery.fileupload.js"></script>
<script>
  $.ajaxSetup({
    headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
  });


  ;(function($){
    'use strict';

    $(document).ready(function(){
      //  
      var $fileupload = $('#fileupload');
      $fileupload.fileupload({
        url: '/dashboard/office-upload',
        formData: {_token: $fileupload.data('token'), officeid: $fileupload.data('officeid')},
        dataType: 'json',
        progressall: function (e, data) {
          var progress = parseInt(data.loaded / data.total * 100, 10);
          $('#progress .progress-bar').css(
            'width',
            progress + '%'
            );
          console.log('teste 3');
        }
      }).bind('fileuploadstop', function (e, data) {
        $('#progress .progress-bar').css(
          'width', '0%'
          );
        location.reload();
      });
      //
    });
  })(window.jQuery);
</script>
@endsection