routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });


 Route::get('/', 'Front\HomeController@maintence');
 Route::get('/manutencao', 'Front\HomeController@index');
 Route::get('escritorio', 'Front\OfficeController@index');
 Route::get('atuacao', 'Front\ActuationsController@index');
 Route::get('atuacao/{slugAtuacao}', 'Front\ActuationsController@show');
 Route::get('/profissionais', 'Front\ProfessionalsController@index');

 Route::get('noticias', 'Front\BlogsController@index');
 Route::get('noticias/{slugBlog}', 'Front\BlogsController@show');
 Route::get('/depoimentos', 'Front\ReviewController@index');
 Route::post('/depoimentos-create', 'Front\ReviewController@store');
 Route::get('/contato', 'Front\ContactController@index');


// Route::get('/reservas', 'Front\ReservationController@index');
// Route::get('/banco-reservas', 'Front\ReservationController@view')->name('bank.index');
// Route::get('/banco-reservas/{name}', 'Front\ReservationController@show')->name('bank.show');
// Route::get('/banco-reservas/{name}/info/{reservation}', 'Front\ReservationController@info')->name('bank.info');

 Route::prefix('services')->namespace('Services')->group(function() {
     Route::post('send-mail', 'MailController@sendContact');
//     Route::prefix('newsletter')->group(function() {
//         Route::post('/', 'MailController@subscribe');
//         Route::get('confirm/{code}', 'MailController@confirmSubscribe');
//     });
//     Route::apiResource('pre-registration', 'PreRegistrationController');
//     Route::get('reservations', 'ReservationsController@index');
//     Route::delete('reservations/{reservation}', 'ReservationsController@destroy');
//     Route::match(['patch','put'], 'reservations', 'ReservationsController@update');

//     Route::post('bank-reservations/{reservation}/interest', 'BankReservationController@interest');
//     Route::delete('bank-reservations/interest/{reservation_interest}', 'BankReservationController@destroy');
//     Route::match(['patch','put'],'bank-reservations/interest/{reservation_interest}', 'BankReservationController@update');
 });


Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');
    Route::resource('office', 'Admin\OfficeController');
    Route::get('office-photos', ['as' => 'office-photos', 'uses' => 'Admin\OfficeController@photos']);
    Route::post('office-upload', ['as' => 'office-upload', 'uses' => 'Admin\OfficeController@upload']);
    Route::get('office-download/{officeId}/{photoId}', ['as' => 'office-download', 'uses' => 'Admin\OfficeController@download']);
	Route::get('office-destroy/{officeId}/{photoId}', ['as' => 'office-destroy', 'uses' => 'Admin\OfficeController@destroy']);


	Route::resource('actuations', 'Admin\ActuationsController');
	Route::resource('professionals', 'Admin\ProfessionalsController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::resource('reviews', 'Admin\ReviewsController');


    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('clients', 'Admin\ClientsController');
	Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    Route::view('pre-registrations', 'admin.pre-registrations.index')->name('pre-registrations.index');
    Route::get('reservations', 'Admin\ReservationsController@index')->name('reservations.index');
    Route::match(['GET', 'POST'], 'reservations/new', 'Admin\ReservationsController@insert')->name('reservations.insert');
    Route::match(['GET', 'PUT'],'reservations/{reservation}', 'Admin\ReservationsController@viewOrUpdate')->name('reservations.viewOrUpdate');
    Route::get('reservations/{id}/ficha', 'Admin\ReservationsController@create')->name('reservations.create');
    Route::post('reservations/{id}/ficha', 'Admin\ReservationsController@store')->name('reservations.store');
});

Auth::routes();

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
    	'name',
    	'link',
    	'status',
    	'image'
    ];
}

app/Http/Controllers/Admin/ClientsController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\Clients\StoreRequest;
use App\Http\Requests\Admin\Clients\UpdateRequest;

use App\Models\Client;

class ClientsController extends Controller
{
    /**
     * Armazena uma nova instancia do model client
     *
     * @var \App\client
     */
    private $clients;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
        $this->clients = app(Client::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clients = Client::orderBy($request->input('sort', 'created_at'), 'ASC')->paginate();
        return view('admin.clients.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $client = new Client;

        $foto_antiga = $client->image;

        if(Storage::has($foto_antiga)){
          Storage::delete($foto_antiga);
        }

        $file = $request->file('image');

        if(!$file->isValid()) {
          abort(400, 'Imagem não encontrada ou não é válida');
        }

        $arquivo = $file->store('clientes');
        $client->image = $arquivo;


        $client->name = $request->name;
        $client->link = $request->link;
        $client->status = $request->status;

        if(!$client->save()) {
            session()->flash('messages.error', ['Houve um erro. Tente novamente!']);
            return redirect()->route('clients.index');
        }

        session()->flash('messages.success', ['Clientes cadastrado com sucesso!']);
        return redirect()->route('clients.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = Client::findOrFail($id);
        return view('admin.clients.show', compact('client'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view('admin.clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreRequest $request, $id)
    {
         $client = $this->clients->where('id', $id)->first();

        if(!$client) {
            session()->flash('messages.error', ['Cliente não existe!']);
            return redirect()->route('clients.index');
        }

      if(!Input::hasFile('image') == null){
        $foto_antiga = $client->image;

        if(Storage::has($foto_antiga)){
          Storage::delete($foto_antiga);
        }

        $file = $request->file('image');

        if(!$file->isValid()) {
          abort(400, 'Imagem não encontrada ou não é válida');
        }

        $arquivo = $file->store('clientes');
        $client->image = $arquivo;
      }

        $client->name = $request->name;
        $client->link = $request->link;
        $client->status = $request->status;
        $client->save();

        session()->flash('messages.success', ['Cliente alterado com sucesso!']);
        return redirect()->route('clients.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
  public function destroy(Request $request, Client $client)
  {

    $client->delete();

    return response(null, 204);
    //return response()->redirectToRoute('blogs.index');
  }
}

resources/views/admin/clients/create.blade.php
@extends('admin.base')
@section('title', 'Novo Cliente')

@section('content')
<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('clients.index') }}">Página de Clientes</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            @yield('title')
          </div>

          <div class="panel-body">

            <form action="{{ route('clients.store')}}" enctype="multipart/form-data" method="POST">
             @include('admin.clients.form')
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
/* BOOTSTRAP WYSIHTML5 */
$('.textarea').wysihtml5();

/* SUMMERNOTE*/
$(document).ready(function() {
  $('.summernote').summernote();
});
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
$('input[name="title"]').stringToSlug({
  setEvents: 'keyup keydown blur',
  getPut: 'input[name="slug"]',
  space: '-',
  replace: '/\s?\([^\)]*\)/gi',
AND: 'e'
});
</script>
@endsection

resources/views/admin/clients/edit.blade.php
@extends('admin.base')
@section('title', 'Editar Cliente')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $client->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('clients.index') }}">Página de Clientes</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End client Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title') - {{ $client->title }}
          </div>

          <div class="panel-body">

            <form action="{{ route('clients.update', $client->id)}}" enctype="multipart/form-data" method="POST">
              <input type="hidden" name="_method" value="PUT">
             @include('admin.clients.form')
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
/* BOOTSTRAP WYSIHTML5 */
$('.textarea').wysihtml5();

/* SUMMERNOTE*/
$(document).ready(function() {
  $('.summernote').summernote();
});
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
$('input[name="title"]').stringToSlug({
  setEvents: 'keyup keydown blur',
  getPut: 'input[name="slug"]',
  space: '-',
  replace: '/\s?\([^\)]*\)/gi',
AND: 'e'
});
</script>
@endsection

resources/views/admin/clients/form.blade.php
{!! csrf_field() !!}

<div class="row">
  <div class="col-md-2">
    <img src="/storage/{{ $client->image ?? old('image') }}" alt="Cliente" class="img-thumbnail">    
  </div>
  <div class="col-md-10">
    <div class="form-group @if ($errors->has('image')) has-error @endif">
      <label for="image" class="form-label">Imagem do Cliente</label>
      <input type="file" class="form-control" id="image" name="image" value="{{ $client->image ?? old('image') }}">
      @if ($errors->has('image'))
      <span class="help-block">
        <strong>{{ $errors->first('image') }}</strong>
      </span>
      @endif
    </div><!-- form-group -->
  </div>
</div>

<hr class="invisible">

<div class="form-group @if ($errors->has('name')) has-error @endif">
  <label for="name" class="form-label">Nome do Cliente</label>
  <input type="text" class="form-control" id="name" name="name" value="{{ $client->name ?? old('name') }}" placeholder="Nome do Cliente" autofocus>
  @if ($errors->has('name'))
  <span class="help-block">
    <strong>{{ $errors->first('name') }}</strong>
  </span>
  @endif
</div><!-- form-group -->

<div class="form-group @if ($errors->has('link')) has-error @endif">
  <label for="link" class="form-label">Link do Cliente</label>
  <input type="text" class="form-control" id="link" name="link" value="{{ $client->link ?? old('link') }}" placeholder="URL do Cliente">
  @if ($errors->has('link'))
  <span class="help-block">
    <strong>{{ $errors->first('link') }}</strong>
  </span>
  @endif
</div><!-- form-group -->


<div class="form-group @if ($errors->has('status')) has-error @endif">
  <label for="status" class="form-label">Status do Cliente</label>
  <select class="form-control" id="status" name="status">
    @if(isset($client->status))
      @if($client->status == 0 )
        <option value="0" selected>Desabilitado</option> 
        <option value="1">Habilitar</option>
      @else
        <option value="0">Desabilitar</option> 
        <option value="1" selected>Habilitado</option>
      @endif
    @else
        <option value="1" selected>Habilitado</option>
        <option value="0">Desabilitado</option> 
    @endif
  </select>

  @if ($errors->has('status'))
  <span class="help-block">
    <strong>{{ $errors->first('status') }}</strong>
  </span>
  @endif
</div><!-- form-group -->

<div class="row">
  <div class="col-md-6">
    <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
    <a href="{{ route('clients.index') }}" class="btn btn-sm btn-warning"><i class="fa fa-reply"></i>Cancelar</a>
  </div><!-- col-md-6 -->
</div>

resources/views/admin/clients/index.blade.php
@extends('admin.base')
@section('title', 'Páginas de Clientes')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard/') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  @include('elements.messages')

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            Lista de @yield('title')
          </div>

            <div class="panel-body">
              <div class="table-responsive">
                 @if(count($clients) > 0)
                <table class="table table-hover table-bordered table-striped" id="clients-table">
                  <thead>
                    <tr>
                      <td width="5%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'id']) }}">#</a></td>
                      <td width="6%">Imagem</td>
                      <td><a href="{{ Request::fullUrlWithQuery(['sort' => 'title']) }}">Title</a></td>
                      <td width="10%">Status</td>
                      <td width="14%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'created_at']) }}">Criação</a></td>
                      <td width="14%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'updated_at']) }}">Alteração</a></td>
                      <td width="15%" class="text-right">Ações</td>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($clients as $client)
                    <tr id="row-{{ $client->id }}">
                      <td>
                        <div class="checkbox">
                          <input class="clients" id="checkbox{{ $client->id }}" data-id="{{ $client->id }}" type="checkbox">
                          <label for="checkbox{{ $client->id }}">
                            <b>{{ $client->id }}</b>
                          </label>
                        </div>
                      </td>
                      <td><img src="/storage/{{ $client->image ?? old('image') }}" alt="Clientes" class="img-thumbnail"> </td>
                      <td>{{ $client->name }}</td>
                      <td>
                        @if($client->status == 0)
                        <span class="label label-danger">Desabilitado</span>
                        @else
                        <span class="label label-success">Habilitado</span>
                        @endif
                      </td>
                      <td>{{ \Carbon\Carbon::parse($client->created_at)->format('d/m/y H:i')  }}</td>
                      <td>{{ \Carbon\Carbon::parse($client->updated_at)->format('d/m/y H:i') }}</td>
                      <td class="text-right">
                        <a href="{{ route('clients.show', $client->id) }}" class="btn btn-xs btn-default btn-icon" data-toggle="tooltip" data-original-title="Detalhes"><i class="fa fa-book"></i></a>
                        <a href="{{ route('clients.edit', $client->id) }}" class="btn btn-xs btn-primary btn-icon" data-toggle="tooltip" data-original-title="Editar"><i class="fa fa-edit"></i></a>
                        <a href="#" class="btn btn-xs btn-danger btn-icon btn-delete" data-id="{{ $client->id }}" data-toggle="tooltip" data-original-title="Remover"><i class="fa fa-remove"></i></a></li>
                      </td>
                    </tr>
                    @endforeach

                  </tbody>
                </table>
                @else
                    <div class="alert alert-info">Nenhum cliente cadastrado.</div>
                @endif

                <hr>

              </div><!-- table-responsive -->
            </div><!-- panel-body -->

            <div class="row">
              <div class="col-md-6">
                <a href="{{ route('clients.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i>Novo</a>
                <a href="#" class="btn btn-sm btn-danger btn-remove-all"><i class="fa fa-remove"></i>Remover selecionados</a>
              </div><!-- col-md-6 -->

              <div class="col-md-6 text-right">
                {{ $clients->links() }}
              </div><!-- col-md-6 -->
            </div>
            

          </div><!-- panel-default -->
        </div><!-- col-md-12 -->
        

      </div><!-- row -->
    </div><!-- container-padding -->

  </div><!-- container-default -->
  <!-- END CONTAINER -->
  @endsection


  @section('cssPage')
  @endsection

  @section('jsPage')
  <script>
    $(function() {
      let btn = $('.btn-delete');
      let btnAll = $('.btn-remove-all');

      function remove(id) {
        let tr = $('#clients-table #row-' + id);
        let request = $.ajax({
         url: '/dashboard/clients/' + id,
         type: 'DELETE',
         statusCode: {
           204: function() {
               tr.fadeOut();
           },
           403: function() {
             let copy = tr.innerHTML;

             tr.html('').append('<td colspan="7">Esse cliente não foi removido.</td>')
                        .css({'background-color': 'red','color': 'white', 'text-align': 'center'});
           }
         }
        });
        return request;
      }

      btn.on('click', function(e) {
        e.preventDefault();
        let action = $(e.currentTarget);
        let request = remove(action.data('id'));
        request.fail(function() {
          window.alert('Não foi possivel remover o cliente')
        });
      })

      btnAll.on('click', function(e) {
        e.preventDefault();

        let checkbox = $('input:checkbox[class="clients"]:checked');

        if(checkbox.length > 0 && window.confirm('Gostaria de remover o(s) ' + checkbox.length + ' selecionado(s) cliente(s)?')) {
          //
          checkbox.each(function(index, el) {
            let id = $(el).data('id')
            let request = remove(id);
          })
        }

      })
    })
  </script>
  @endsection

resources/views/admin/clients/show.blade.php
@extends('admin.base')
@section('title', 'Detalhes do Cliente')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $service->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('services.index') }}">Página de Clientes</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End service Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            <h2>{{ $service->title }}</h2>
          </div>

          <div class="panel-body">

            <img src="/storage/{{ $service->image ?? old('image') }}" alt="Clientes" class="img-thumbnail">

            <p><small>Criado em {{ $service->created_at->format('d/m/Y H:i:s') }} | Atualizado em {{ $service->updated_at->format('d/m/Y H:i:s') }}</small></p>
            <blockquote>{!! $service->body !!}</blockquote>

            <hr>

            <a href="{{ route('services.index') }}" class="btn btn-xs btn-warning">Voltar</a>
            <a href="{{ route('services.edit', $service->id) }}" class="btn btn-xs btn-primary">Editar</a>
            <a href="{{ route('services.destroy', $service->id) }}" class="btn btn-xs btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form-services').submit();"><i class="fa fa-remove"></i> Deletar</a></li>
            <form id="delete-form-services" action="{{ route('services.destroy', $service->id) }}" method="POST" style="display: none;">
             {!! csrf_field() !!}
             <input type="hidden" name="_method" value="DELETE">
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
@endsection