routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });


 Route::get('/', 'Front\HomeController@maintence');
 Route::get('/manutencao', 'Front\HomeController@index');
 Route::get('escritorio', 'Front\OfficeController@index');
 Route::get('atuacao', 'Front\ActuationsController@index');
 Route::get('atuacao/{slugAtuacao}', 'Front\ActuationsController@show');
 Route::get('/profissionais', 'Front\ProfessionalsController@index');

 Route::get('noticias', 'Front\BlogsController@index');
 Route::get('noticias/{slugBlog}', 'Front\BlogsController@show');
 Route::get('/depoimentos', 'Front\ReviewController@index');
 Route::post('/depoimentos-create', 'Front\ReviewController@store');
 Route::get('/contato', 'Front\ContactController@index');


// Route::get('/reservas', 'Front\ReservationController@index');
// Route::get('/banco-reservas', 'Front\ReservationController@view')->name('bank.index');
// Route::get('/banco-reservas/{name}', 'Front\ReservationController@show')->name('bank.show');
// Route::get('/banco-reservas/{name}/info/{reservation}', 'Front\ReservationController@info')->name('bank.info');

 Route::prefix('services')->namespace('Services')->group(function() {
     Route::post('send-mail', 'MailController@sendContact');
//     Route::prefix('newsletter')->group(function() {
//         Route::post('/', 'MailController@subscribe');
//         Route::get('confirm/{code}', 'MailController@confirmSubscribe');
//     });
//     Route::apiResource('pre-registration', 'PreRegistrationController');
//     Route::get('reservations', 'ReservationsController@index');
//     Route::delete('reservations/{reservation}', 'ReservationsController@destroy');
//     Route::match(['patch','put'], 'reservations', 'ReservationsController@update');

//     Route::post('bank-reservations/{reservation}/interest', 'BankReservationController@interest');
//     Route::delete('bank-reservations/interest/{reservation_interest}', 'BankReservationController@destroy');
//     Route::match(['patch','put'],'bank-reservations/interest/{reservation_interest}', 'BankReservationController@update');
 });


Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');
    Route::resource('office', 'Admin\OfficeController');
    Route::get('office-photos', ['as' => 'office-photos', 'uses' => 'Admin\OfficeController@photos']);
    Route::post('office-upload', ['as' => 'office-upload', 'uses' => 'Admin\OfficeController@upload']);
    Route::get('office-download/{officeId}/{photoId}', ['as' => 'office-download', 'uses' => 'Admin\OfficeController@download']);
	Route::get('office-destroy/{officeId}/{photoId}', ['as' => 'office-destroy', 'uses' => 'Admin\OfficeController@destroy']);


	Route::resource('actuations', 'Admin\ActuationsController');
	Route::resource('professionals', 'Admin\ProfessionalsController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::resource('reviews', 'Admin\ReviewsController');


    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('clients', 'Admin\ClientsController');
	Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    Route::view('pre-registrations', 'admin.pre-registrations.index')->name('pre-registrations.index');
    Route::get('reservations', 'Admin\ReservationsController@index')->name('reservations.index');
    Route::match(['GET', 'POST'], 'reservations/new', 'Admin\ReservationsController@insert')->name('reservations.insert');
    Route::match(['GET', 'PUT'],'reservations/{reservation}', 'Admin\ReservationsController@viewOrUpdate')->name('reservations.viewOrUpdate');
    Route::get('reservations/{id}/ficha', 'Admin\ReservationsController@create')->name('reservations.create');
    Route::post('reservations/{id}/ficha', 'Admin\ReservationsController@store')->name('reservations.store');
});

Auth::routes();

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = [
    	'title',
    	'url',
    	'image'
    ];
}

app/Http/Controllers/Admin/SlidersController.php
<?php

namespace App\Http\Controllers\Admin;

use Validator;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Admin\Sliders\StoreRequest;
use App\Http\Requests\Admin\Sliders\UpdateRequest;

use App\Models\Slider;

class SlidersController extends Controller
{
    /**
     * Armazena uma nova instancia do model slider
     *
     * @var \App\slider
     */
    private $sliders;

    /**
     * Metodo construtor.
     */
    public function __construct()
    {
        $this->sliders = app(Slider::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sliders = Slider::orderBy($request->input('sort', 'created_at'), 'ASC')->paginate();
        return view('admin.sliders.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.sliders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $slider = new Slider;

        $foto_antiga = $slider->image;

        if(Storage::has($foto_antiga)){
          Storage::delete($foto_antiga);
        }

        $file = $request->file('image');

        if(!$file->isValid()) {
          abort(400, 'Imagem não encontrada ou não é válida');
        }

        $arquivo = $file->store('sliders');
        $slider->image = $arquivo;


        $slider->title = $request->title;
        $slider->url = $request->url;

        if(!$slider->save()) {
            session()->flash('messages.error', ['Houve um erro. Tente novamente!']);
            return redirect()->route('sliders.index');
        }

        session()->flash('messages.success', ['Slider cadastrado com sucesso!']);
        return redirect()->route('sliders.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $slider = Slider::findOrFail($id);
        return view('admin.sliders.show', compact('slider'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::findOrFail($id);
        return view('admin.sliders.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreRequest $request, $id)
    {
         $slider = $this->sliders->where('id', $id)->first();

        if(!$slider) {
            session()->flash('messages.error', ['Slider não existe!']);
            return redirect()->route('sliders.index');
        }

      if(!Input::hasFile('image') == null){
        $foto_antiga = $slider->image;

        if(Storage::has($foto_antiga)){
          Storage::delete($foto_antiga);
        }

        $file = $request->file('image');

        if(!$file->isValid()) {
          abort(400, 'Imagem não encontrada ou não é válida');
        }

        $arquivo = $file->store('sliders');
        $slider->image = $arquivo;
      }

        $slider->title = $request->title;
        $slider->url = $request->url;
        $slider->save();

        session()->flash('messages.success', ['Slider alterado com sucesso!']);
        return redirect()->route('sliders.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Slider::findOrFail($id);
        $slider->delete();
        return response()->redirectToRoute('sliders.index');
    }
}

resources/views/admin/sliders/create.blade.php
@extends('admin.base')
@section('title', 'Novo Slider')

@section('content')
<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('sliders.index') }}">Página de Sliders</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            @yield('title')
          </div>

          <div class="panel-body">

            <form action="{{ route('sliders.store')}}" enctype="multipart/form-data" method="POST">
             @include('admin.sliders.form')
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
/* BOOTSTRAP WYSIHTML5 */
$('.textarea').wysihtml5();

/* SUMMERNOTE*/
$(document).ready(function() {
  $('.summernote').summernote();
});
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
$('input[name="title"]').stringToSlug({
  setEvents: 'keyup keydown blur',
  getPut: 'input[name="slug"]',
  space: '-',
  replace: '/\s?\([^\)]*\)/gi',
AND: 'e'
});
</script>
@endsection

resources/views/admin/sliders/edit.blade.php
@extends('admin.base')
@section('title', 'Editar Slider')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $slider->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('sliders.index') }}">Página de Sliders</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End slider Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
           @yield('title') - {{ $slider->title }}
          </div>

          <div class="panel-body">

            <form action="{{ route('sliders.update', $slider->id)}}" enctype="multipart/form-data" method="POST">
              <input type="hidden" name="_method" value="PUT">
             @include('admin.sliders.form')
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
<!-- ================================================
Bootstrap WYSIHTML5
================================================ -->
<!-- main file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/wysihtml5-0.3.0.min.js"></script>
<!-- bootstrap file -->
<script type="text/javascript" src="/backend/js/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>

<!-- ================================================
Summernote
================================================ -->
<script type="text/javascript" src="/backend/js/summernote/summernote.min.js"></script>

<script>
/* BOOTSTRAP WYSIHTML5 */
$('.textarea').wysihtml5();

/* SUMMERNOTE*/
$(document).ready(function() {
  $('.summernote').summernote();
});
</script>

<!-- Query String ToSlug - Transforma o titulo em URL amigavel sem acentos ou espaço -->
<script type="text/javascript" src="/backend/js/jquery.stringToSlug.min.js"></script>
<script type="text/javascript">
$('input[name="title"]').stringToSlug({
  setEvents: 'keyup keydown blur',
  getPut: 'input[name="slug"]',
  space: '-',
  replace: '/\s?\([^\)]*\)/gi',
AND: 'e'
});
</script>
@endsection

resources/views/admin/sliders/form.blade.php
{!! csrf_field() !!}

<div class="row">
  <div class="col-md-2">
    <img src="/storage/{{ $slider->image ?? old('image') }}" alt="Sliders" class="img-thumbnail">    
  </div>
  <div class="col-md-10">
    <div class="form-group @if ($errors->has('image')) has-error @endif">
      <label for="image" class="form-label">Imagem do Slider</label>
      <input type="file" class="form-control" id="image" name="image" value="{{ $slider->image ?? old('image') }}">
      @if ($errors->has('image'))
      <span class="help-block">
        <strong>{{ $errors->first('image') }}</strong>
      </span>
      @endif
    </div><!-- form-group -->
  </div>
</div>

<hr class="invisible">

<div class="form-group @if ($errors->has('title')) has-error @endif">
  <label for="title" class="form-label">Título do Slider</label>
  <input type="text" class="form-control" id="title" name="title" value="{{ $slider->title ?? old('title') }}" placeholder="Título do Slider" autofocus>
  @if ($errors->has('title'))
  <span class="help-block">
    <strong>{{ $errors->first('title') }}</strong>
  </span>
  @endif
</div><!-- form-group -->

<div class="form-group @if ($errors->has('url')) has-error @endif">
  <label for="url" class="form-label">Link do Slider</label>
  <input type="text" class="form-control" id="url" name="url" value="{{ $slider->url ?? old('url') }}" placeholder="URL do Slider" autofocus>
  @if ($errors->has('url'))
  <span class="help-block">
    <strong>{{ $errors->first('url') }}</strong>
  </span>
  @endif
  <span class="help-block">Caso não possui link, deixar em branco.</span>
</div><!-- form-group -->

<div class="row">
  <div class="col-md-6">
    <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-check"></i>Salvar</button>
    <a href="{{ route('sliders.index') }}" class="btn btn-sm btn-warning"><i class="fa fa-reply"></i>Cancelar</a>
  </div><!-- col-md-6 -->
</div>

resources/views/admin/sliders/index.blade.php
@extends('admin.base')
@section('title', 'Páginas de Slider')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title')</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard/') }}">Inicio</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End Page Header -->


<!-- START CONTAINER -->
<div class="container-default">

  @include('elements.messages')

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            Lista de @yield('title')
          </div>

            <div class="panel-body">
              <div class="table-responsive">
                 @if(count($sliders) > 0)
                <table class="table table-hover table-bordered table-striped">
                  <thead>
                    <tr>
                      <td width="5%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'id']) }}">#</a></td>
                      <td width="6%">Imagem</td>
                      <td><a href="{{ Request::fullUrlWithQuery(['sort' => 'title']) }}">Title</a></td>
                      <td width="14%"><a href="{{ Request::fullUrlWithQuery(['sort' => 'created_at']) }}">Criação</a></td>
                      <td width="15%" class="text-right">Ações</td>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($sliders as $slider)
                    <tr>
                      <td>
                        <div class="checkbox">
                          <input id="checkbox{{ $slider->id }}" type="checkbox">
                          <label for="checkbox{{ $slider->id }}">
                            <b>{{ $slider->id }}</b>
                          </label>
                        </div>
                      </td>
                      <td><img src="/storage/{{ $slider->image ?? old('image') }}" alt="Slider" class="img-thumbnail"> </td>
                      <td>{{ $slider->title }}</td>
                      <td>{{ \Carbon\Carbon::parse($slider->created_at)->format('d/m/y H:i')  }}</td>
                      <td class="text-right">
                        <a href="{{ route('sliders.edit', $slider->id) }}" class="btn btn-xs btn-primary btn-icon" data-toggle="tooltip" data-original-title="Editar"><i class="fa fa-edit"></i></a>
                        <a href="{{ route('sliders.destroy', $slider->id) }}" class="btn btn-xs btn-danger btn-icon" onclick="event.preventDefault(); document.getElementById('delete-form-sliders-list').submit();" data-toggle="tooltip" data-original-title="Remover"><i class="fa fa-remove"></i></a></li>
                       <form id="delete-form-sliders-list" action="{{ route('sliders.destroy', $slider->id) }}" method="POST" style="display: none;">
                           {!! csrf_field() !!}
                           <input type="hidden" name="_method" value="DELETE">
                       </form>
                      </td>
                    </tr>
                    @endforeach

                  </tbody>
                </table>
                @else
                    <div class="alert alert-info">Nenhum slider cadastrado.</div>
                @endif

                <hr>

              </div><!-- table-responsive -->
            </div><!-- panel-body -->

            <div class="row">
              <div class="col-md-6">
                <a href="{{ route('sliders.create') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i>Novo</a>
                <a href="#" class="btn btn-sm btn-danger"><i class="fa fa-remove"></i>Remover selecionados</a>
              </div><!-- col-md-6 -->

              <div class="col-md-6 text-right">
                {{ $sliders->links() }}
              </div><!-- col-md-6 -->
            </div>
            

          </div><!-- panel-default -->
        </div><!-- col-md-12 -->
        

      </div><!-- row -->
    </div><!-- container-padding -->

  </div><!-- container-default -->
  <!-- END CONTAINER -->
  @endsection


  @section('cssPage')
  @endsection

  @section('jsPage')
  @endsection

resources/views/admin/sliders/show.blade.php
@extends('admin.base')
@section('title', 'Detalhes do Slider')

@section('content')


<!-- Start Page Header -->
<div class="page-header">
  <h1 class="title">@yield('title') - {{ $slider->title }}</h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/dashboard') }}">Inicio</a></li>
    <li><a href="{{ route('sliders.index') }}">Página de Sliders</a></li>
    <li class="active">@yield('title')</li>
  </ol>
</div>
<!-- End slider Header -->


<!-- START CONTAINER -->
<div class="container-default">

  <div class="container-padding">
    <div class="row">

      <div class="col-md-12">
        <div class="panel panel-default">

          <div class="panel-title">
            <h2>{{ $slider->title }}</h2>
          </div>

          <div class="panel-body">

            <img src="/storage/{{ $slider->image ?? old('image') }}" alt="Sliders" class="img-thumbnail">

            <p><small>Criado em {{ $slider->created_at->format('d/m/Y H:i:s') }} | Atualizado em {{ $slider->updated_at->format('d/m/Y H:i:s') }}</small></p>
            <blockquote>{!! $slider->body !!}</blockquote>

            <hr>

            <a href="{{ route('sliders.index') }}" class="btn btn-xs btn-warning">Voltar</a>
            <a href="{{ route('sliders.edit', $slider->id) }}" class="btn btn-xs btn-primary">Editar</a>
            <a href="{{ route('sliders.destroy', $slider->id) }}" class="btn btn-xs btn-danger" onclick="event.preventDefault(); document.getElementById('delete-form-sliders').submit();"><i class="fa fa-remove"></i> Deletar</a></li>
            <form id="delete-form-sliders" action="{{ route('sliders.destroy', $slider->id) }}" method="POST" style="display: none;">
             {!! csrf_field() !!}
             <input type="hidden" name="_method" value="DELETE">
           </form>

         </div><!-- panel-body -->


       </div><!-- panel-default -->
     </div><!-- col-md-12 -->


   </div><!-- row -->
 </div><!-- container-padding -->

</div><!-- container-default -->
<!-- END CONTAINER -->
@endsection

@section('cssPage')
@endsection

@section('jsPage')
@endsection