routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/webmail', function(){ return redirect('http://webmail.innsystem.com.br/'); });
Route::get('/admin', function(){ return redirect('/dashboard'); });


 Route::get('/', 'Front\HomeController@maintence');
 Route::get('/manutencao', 'Front\HomeController@index');
 Route::get('escritorio', 'Front\OfficeController@index');
 Route::get('atuacao', 'Front\ActuationsController@index');
 Route::get('atuacao/{slugAtuacao}', 'Front\ActuationsController@show');
 Route::get('/profissionais', 'Front\ProfessionalsController@index');

 Route::get('noticias', 'Front\BlogsController@index');
 Route::get('noticias/{slugBlog}', 'Front\BlogsController@show');
 Route::get('/depoimentos', 'Front\ReviewController@index');
 Route::post('/depoimentos-create', 'Front\ReviewController@store');
 Route::get('/contato', 'Front\ContactController@index');


// Route::get('/reservas', 'Front\ReservationController@index');
// Route::get('/banco-reservas', 'Front\ReservationController@view')->name('bank.index');
// Route::get('/banco-reservas/{name}', 'Front\ReservationController@show')->name('bank.show');
// Route::get('/banco-reservas/{name}/info/{reservation}', 'Front\ReservationController@info')->name('bank.info');

 Route::prefix('services')->namespace('Services')->group(function() {
     Route::post('send-mail', 'MailController@sendContact');
//     Route::prefix('newsletter')->group(function() {
//         Route::post('/', 'MailController@subscribe');
//         Route::get('confirm/{code}', 'MailController@confirmSubscribe');
//     });
//     Route::apiResource('pre-registration', 'PreRegistrationController');
//     Route::get('reservations', 'ReservationsController@index');
//     Route::delete('reservations/{reservation}', 'ReservationsController@destroy');
//     Route::match(['patch','put'], 'reservations', 'ReservationsController@update');

//     Route::post('bank-reservations/{reservation}/interest', 'BankReservationController@interest');
//     Route::delete('bank-reservations/interest/{reservation_interest}', 'BankReservationController@destroy');
//     Route::match(['patch','put'],'bank-reservations/interest/{reservation_interest}', 'BankReservationController@update');
 });


Route::prefix('dashboard')->middleware(['auth'])->group(function(){
	Route::get('/', 'Admin\DashboardController@index');
	Route::resource('users', 'Admin\UsersController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('configs', 'Admin\ConfigController');
    Route::resource('office', 'Admin\OfficeController');
    Route::get('office-photos', ['as' => 'office-photos', 'uses' => 'Admin\OfficeController@photos']);
    Route::post('office-upload', ['as' => 'office-upload', 'uses' => 'Admin\OfficeController@upload']);
    Route::get('office-download/{officeId}/{photoId}', ['as' => 'office-download', 'uses' => 'Admin\OfficeController@download']);
	Route::get('office-destroy/{officeId}/{photoId}', ['as' => 'office-destroy', 'uses' => 'Admin\OfficeController@destroy']);


	Route::resource('actuations', 'Admin\ActuationsController');
	Route::resource('professionals', 'Admin\ProfessionalsController');
    Route::resource('blogs', 'Admin\BlogsController');
    Route::resource('reviews', 'Admin\ReviewsController');


    Route::resource('sliders', 'Admin\SlidersController');
    Route::resource('clients', 'Admin\ClientsController');
	Route::prefix('newsletter')->group(function() {
        Route::get('list', 'Admin\NewsletterController@index');
        Route::delete('/{newsletter}', 'Admin\NewsletterController@destroy');
        Route::get('generate-list', 'Admin\NewsletterController@generate');
        Route::view('/', 'admin.newsletter.index')->name('newsletter.index');
    });
    Route::view('pre-registrations', 'admin.pre-registrations.index')->name('pre-registrations.index');
    Route::get('reservations', 'Admin\ReservationsController@index')->name('reservations.index');
    Route::match(['GET', 'POST'], 'reservations/new', 'Admin\ReservationsController@insert')->name('reservations.insert');
    Route::match(['GET', 'PUT'],'reservations/{reservation}', 'Admin\ReservationsController@viewOrUpdate')->name('reservations.viewOrUpdate');
    Route::get('reservations/{id}/ficha', 'Admin\ReservationsController@create')->name('reservations.create');
    Route::post('reservations/{id}/ficha', 'Admin\ReservationsController@store')->name('reservations.store');
});

Auth::routes();

resources/views/admin/includes/sidebar-left.blade.php
<div class="sidebar clearfix">

    <ul class="sidebar-panel nav">
        <li class="sidetitle">NAVEGAÇÃO</li>
        <li><a href="{{ url('/') }}" target="_Blank"><span class="icon color5"><i class="fa fa-desktop"></i></span>Meu Site</a></li>
        <li><a href="{{ url('/dashboard') }}"><span class="icon color5"><i class="fa fa-home"></i></span>Início</a></li>
	<li><a href="http://webmail.innsystem.com.br" target="_Blank"><span class="icon color5"><i class="fa fa-comments"></i></span>Web Mail</a></li>

        <li><a href="#"><span class="icon color7"><i class="fa fa-cogs"></i></span> Configuração <span class="caret"></span></a>
            <ul>
                <li><a href="{{ route('configs.index') }}"><i class="fa fa-cog"></i>Site em Geral</a></li>
                <li><a href="{{ route('users.index') }}"><i class="fa fa-user"></i>Usuários Administrativos</a></li>
            </ul>
        </li>
   

        <li><a href="#"><span class="icon color7"><i class="fa fa-book"></i></span> Páginas <span class="caret"></span></a>
            <ul>
                <li><a href="{{ route('office.index') }}"><i class="fa fa-bank"></i> O Escritório</a></li>
                <li><a href="{{ url('/dashboard/office-photos') }}"><i class="fa fa-camera"></i> Galeria de Fotos</a></li>
                <li><a href="{{ route('actuations.index') }}"><i class="fa fa-cog"></i> Atuação</a></li>
                <li><a href="{{ route('professionals.index') }}"><i class="fa fa-users"></i> Profissional</a></li>
                <li><a href="{{ route('blogs.index') }}"><i class="fa fa-comments"></i> Notícias</a></li>
                <li><a href="{{ route('reviews.index') }}"><i class="fa fa-heart"></i> Depoimentos</a></li>
                <li><a href="{{ route('sliders.index') }}"><i class="fa fa-image"></i> Sliders</a></li>
                @if(Auth::User()->level === 'developer')
                <li><a href="{{ route('pages.index') }}"><i class="fa fa-book"></i> Página de Informações</a></li>
                @endif
            </ul>
        </li>
    </ul>

    <ul class="sidebar-panel nav">
        <li class="sidetitle">OUTROS</li>
        <li><a href="{{ url('https://www.innsystem.com.br/central-ajuda') }}" target="_Blank"><span class="icon color15"><i class="fa fa-bank"></i></span>Central de Ajuda</a></li>
        <li><a href="{{ url('https://www.innsystem.com.br/contato') }}" target="_Blank"><span class="icon color15"><i class="fa fa-tags"></i></span>Ticket de Suporte</a></li>
    </ul>

</div><!-- sidebar -->

resources/views/admin/includes/sidebar-right.blade.php
<div role="tabpanel" class="sidepanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#today" aria-controls="today" role="tab" data-toggle="tab">TODAY</a></li>
    <li role="presentation"><a href="#tasks" aria-controls="tasks" role="tab" data-toggle="tab">TASKS</a></li>
    <li role="presentation"><a href="#chat" aria-controls="chat" role="tab" data-toggle="tab">CHAT</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">

    <!-- Start Today -->
    <div role="tabpanel" class="tab-pane active" id="today">

      <div class="sidepanel-m-title">
        Today
        <span class="left-icon"><a href="#"><i class="fa fa-refresh"></i></a></span>
        <span class="right-icon"><a href="#"><i class="fa fa-file-o"></i></a></span>
      </div>

      <div class="gn-title">NEW</div>

      <ul class="list-w-title">
        <li>
          <a href="#">
            <span class="label label-danger">ORDER</span>
            <span class="date">9 hours ago</span>
            <h4>New Jacket 2.0</h4>
            Etiam auctor porta augue sit amet facilisis. Sed libero nisi, scelerisque.
          </a>
        </li>
        <li>
          <a href="#">
            <span class="label label-success">COMMENT</span>
            <span class="date">14 hours ago</span>
            <h4>Bill Jackson</h4>
            Etiam auctor porta augue sit amet facilisis. Sed libero nisi, scelerisque.
          </a>
        </li>
        <li>
          <a href="#">
            <span class="label label-info">MEETING</span>
            <span class="date">at 2:30 PM</span>
            <h4>Developer Team</h4>
            Etiam auctor porta augue sit amet facilisis. Sed libero nisi, scelerisque.
          </a>
        </li>
        <li>
          <a href="#">
            <span class="label label-warning">EVENT</span>
            <span class="date">3 days left</span>
            <h4>Birthday Party</h4>
            Etiam auctor porta augue sit amet facilisis. Sed libero nisi, scelerisque.
          </a>
        </li>
      </ul>

    </div>
    <!-- End Today -->

    <!-- Start Tasks -->
    <div role="tabpanel" class="tab-pane" id="tasks">

      <div class="sidepanel-m-title">
        To-do List
        <span class="left-icon"><a href="#"><i class="fa fa-pencil"></i></a></span>
        <span class="right-icon"><a href="#"><i class="fa fa-trash"></i></a></span>
      </div>

      <div class="gn-title">TODAY</div>

      <ul class="todo-list">
        <li class="checkbox checkbox-primary">
          <input id="checkboxside1" type="checkbox"><label for="checkboxside1">Add new products</label>
        </li>
        
        <li class="checkbox checkbox-primary">
          <input id="checkboxside2" type="checkbox"><label for="checkboxside2"><b>May 12, 6:30 pm</b> Meeting with Team</label>
        </li>
        
        <li class="checkbox checkbox-warning">
          <input id="checkboxside3" type="checkbox"><label for="checkboxside3">Design Facebook page</label>
        </li>
        
        <li class="checkbox checkbox-info">
          <input id="checkboxside4" type="checkbox"><label for="checkboxside4">Send Invoice to customers</label>
        </li>
        
        <li class="checkbox checkbox-danger">
          <input id="checkboxside5" type="checkbox"><label for="checkboxside5">Meeting with developer team</label>
        </li>
      </ul>

      <div class="gn-title">TOMORROW</div>
      <ul class="todo-list">
        <li class="checkbox checkbox-warning">
          <input id="checkboxside6" type="checkbox"><label for="checkboxside6">Redesign our company blog</label>
        </li>
        
        <li class="checkbox checkbox-success">
          <input id="checkboxside7" type="checkbox"><label for="checkboxside7">Finish client work</label>
        </li>
        
        <li class="checkbox checkbox-info">
          <input id="checkboxside8" type="checkbox"><label for="checkboxside8">Call Johnny from Developer Team</label>
        </li>

      </ul>
    </div>    
    <!-- End Tasks -->

    <!-- Start Chat -->
    <div role="tabpanel" class="tab-pane" id="chat">

      <div class="sidepanel-m-title">
        Friend List
        <span class="left-icon"><a href="#"><i class="fa fa-pencil"></i></a></span>
        <span class="right-icon"><a href="#"><i class="fa fa-trash"></i></a></span>
      </div>

      <div class="gn-title">ONLINE MEMBERS (3)</div>
      <ul class="group">
        <li class="member"><a href="#"><img src="/galerias/avatares/1.png" alt="img"><b>Allice Mingham</b>Los Angeles</a><span class="status online"></span></li>
        <li class="member"><a href="#"><img src="/galerias/avatares/2.png" alt="img"><b>James Throwing</b>Las Vegas</a><span class="status busy"></span></li>
        <li class="member"><a href="#"><img src="/galerias/avatares/3.png" alt="img"><b>Fred Stonefield</b>New York</a><span class="status away"></span></li>
        <li class="member"><a href="#"><img src="/galerias/avatares/4.png" alt="img"><b>Chris M. Johnson</b>California</a><span class="status online"></span></li>
      </ul>

      <div class="gn-title">OFFLINE MEMBERS (8)</div>
     <ul class="group">
        <li class="member"><a href="#"><img src="/galerias/avatares/5.png" alt="img"><b>Allice Mingham</b>Los Angeles</a><span class="status offline"></span></li>
        <li class="member"><a href="#"><img src="/galerias/avatares/6.png" alt="img"><b>James Throwing</b>Las Vegas</a><span class="status offline"></span></li>
      </ul>

      <form class="search">
        <input type="text" class="form-control" placeholder="Search a Friend...">
      </form>
    </div>
    <!-- End Chat -->

  </div>

</div>